[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 7860
maxUploadSize = 200
maxMessageSize = 200
enableWebsocketCompression = false

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[theme]
primaryColor = "#0066cc"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[runner]
magicEnabled = false
fastReruns = true

[client]
showErrorDetails = true
toolbarMode = "minimal"